# https://github.com/actions/starter-workflows/issues/53
name: C/C++ CI

on: [push]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: convert yolo weights
      run: cat yolo9000-weights/x* > yolo9000-weights/yolo9000.weights
    - name: build
      run: cd darknet && make
    - name: run
      run: ./darknet detector test cfg/combine9k.data cfg/yolo9000.cfg ../yolo9000-weights/yolo9000.weights data/horses.jpg

