name: CI

on: [push]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
            submodules: true
    - name: convert yolo weights
      run: cat yolo9000-weights/x* > yolo9000-weights/yolo9000.weights
    - name: build
      run: cd darknet && make
    - name: run
      run: cd darknet && ./darknet detector test cfg/combine9k.data cfg/yolo9000.cfg ../yolo9000-weights/yolo9000.weights data/horses.jpg

  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
      with:
            submodules: true
    - name: convert yolo weights
      run: cat yolo9000-weights/x* > yolo9000-weights/yolo9000.weights
    - name: revert to previous commit for MacOS
      run: cd darknet && git reset --hard b61bcf544e8dbcbd2e978ca6a716fa96b37df767
    - name: build
      run: cd darknet && make
    - name: run
      run: cd darknet && ./darknet detector test cfg/combine9k.data cfg/yolo9000.cfg ../yolo9000-weights/yolo9000.weights data/horses.jpg

